---
- name: Set up Numix icons and theme
  hosts: localhost

  tasks:
    - name: Install Numix icons and themes
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - numix-blue-gtk-theme
        - numix-icon-theme

    - name: Set XFCE theme to Numix Blue
      command: xfconf-query -c xsettings -p /Net/ThemeName -s "NumixBlue"

    - name: Set XFCE icon theme to Numix
      command: xfconf-query -c xsettings -p /Net/IconThemeName -s "Numix"

    - name: Set XFCE window manager theme to Numix Blue
      command: xfconf-query -c xfwm4 -p /general/theme -s "NumixBlue"
