---
- name: Set up Boostnote note taking application
  hosts: localhost
  vars:
    appVersion: "0.11.15"
    appPackage: "boostnote_{{appVersion}}_amd64.deb"
    appPackageUrl: "https://github.com/BoostIO/boost-releases/releases/download/v{{appVersion}}/{{appPackage}}"

  tasks:
    - name: Install Boostnote note taking application from web
      become: yes
      become_user: root
      become_method: sudo
      apt:
        deb: "{{appPackageUrl}}"
