---
- name: Set up Docker containerization (https://www.docker.com/)
  hosts: localhost

  tasks:
    - name: Uninstall old version
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: "{{item}}"
        state: absent
      with_items:
        - docker
        - docker-engine
        - docker.io

    - name: Install packages to allow apt to use a repository over HTTPS
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key to allow apt to authenticate the Docker repository
      become: yes
      become_user: root
      become_method: sudo
      apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         id: 0EBFCD88
         state: present
         validate_certs: yes

    - name: Add Docker APT list
      become: yes
      become_user: root
      become_method: sudo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker

    - name: Install Docker
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - docker-ce
        - docker-compose

    - name: Add the current user to the 'docker' group
      become: yes
      become_user: root
      become_method: sudo
      command: usermod -aG docker {{ansible_user_id}}
