---
- name: Set up Fish shell
  hosts: localhost

  tasks:
    - name: Install Fish shell
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - fish

    - name: Set fish as default shell
      become: yes
      become_user: root
      become_method: sudo
      command: chsh -s /usr/bin/fish {{ansible_user_id}}
