---
- name: Set up Fish shell
  hosts: localhost

  tasks:
    - name: Install Fish shell
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - fish
        - curl

    - name: Set fish as default shell for current user
      become: yes
      become_user: root
      become_method: sudo
      command: chsh -s /usr/bin/fish {{ansible_user_id}}

    - name: Create ~/.config/fish/functions
      file:
        path: "/home/{{ansible_user_id}}/.config/fish/functions"
        state: directory

    - name: Install Fisherman, the fish-shell plugin manager
      get_url:
        url: https://git.io/fisher
        dest: "/home/{{ansible_user_id}}/.config/fish/functions/fisher.fish"

    - name: Add Fish plugins
      command: fish -c "fisher add {{item}}"
      with_items:
        - patrickf3139/Colored-Man-Pages
        - brgmnn/fish-docker-compose
