---
- name: Set up homeshick dotfiles synchronizer
  hosts: localhost

  tasks:
    - name: Install homeshick dotfiles synchronizer
      command: git clone git://github.com/andsens/homeshick.git /home/{{ansible_user_id}}/.homesick/repos/homeshick

    - name: Create ~/.config/fish/config.fish
      file:
        path: "/home/{{ansible_user_id}}/.config/fish/config.fish"
        state: touch

    - name: Add homeshick completion for Fish shell
      shell: echo '\n. "/home/{{ansible_user_id}}/.homesick/repos/homeshick/homeshick.fish"' >> "/home/{{ansible_user_id}}/.config/fish/config.fish"
