---
- name: Set up Insync Google Drive desktop integration (https://www.insynchq.com/)
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Add Insync GPG key to allow apt to authenticate the Insync repository
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: ACCAF35C
        state: present
        validate_certs: yes

    - name: Add Insync APT list
      apt_repository:
        repo: deb http://apt.insynchq.com/ubuntu bionic non-free contrib
        state: present
        filename: insync

    - name: Install Insync Google Drive client
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - insync
        - insync-thunar
