---
- name: Install Ubuntu provided packages
  hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      become_user: root
      become_method: sudo
      apt: name={{item}} state=present
      with_items:
        # sytem utils
        - gparted
        - usb-creator-gtk
        - htop
        - iotop
        - dstat
        # programming
        - meld
