---
- name: Install Ubuntu provided packages
  hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        # sytem utils
        - usb-creator-gtk
        - htop
        - iotop
        - dstat
        # disk utils
        - gparted
        - gnome-disk-utility
        - smartmontools
        # programming
        - meld
        # files
        - mc
        # images
        - catimg
        # desktop utils
        - synapse
        # drawing utils
        - graphviz
