---
- name: Install Ubuntu provided packages
  hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name:
          # sytem utils
          - usb-creator-gtk
          - htop
          - iotop
          - dstat
          # disk utils
          - gparted
          - gnome-disk-utility
          - smartmontools
          # programming
          - meld
          # files
          - mc
          # images
          - catimg
          - gimp
          # desktop utils
          - synapse
          # drawing utils
          - graphviz
        state: present
        update_cache: yes
