---
- name: Set up Skype
  hosts: localhost

  tasks:
    - name: Install Skype from web
      become: yes
      become_user: root
      become_method: sudo
      apt:
        deb: https://go.skype.com/skypeforlinux-64.deb
