---
- name: Set up Skype messaging application (https://www.skype.com/)
  hosts: localhost

  tasks:
    - name: Install Skype messaging application from web
      become: yes
      become_user: root
      become_method: sudo
      apt:
        deb: https://go.skype.com/skypeforlinux-64.deb
