---
- name: Install Terminator terminal emulator
  hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name:
          - terminator
        state: present
        update_cache: yes
