---
- name: Update system to latest
  hosts: localhost

  tasks:
    - name: Install updates
      become: yes
      become_user: root
      become_method: sudo
      apt:
        autoremove: yes
        update_cache: yes
        upgrade: full
