---
- name: Set up Virtualbox virtualizer (https://www.virtualbox.org/)
  hosts: localhost
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Add VirtualBox GPG key to allow apt to authenticate the VirtualBox repository
      apt_key:
         url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
         id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
         state: present
         validate_certs: yes

    - name: Add Virtualbox APT list
      apt_repository:
        repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib
        state: present
        filename: virtualbox

    - name: Install VirtualBox
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      with_items:
        - virtualbox-5.2
