---
- name: Set up Zoom video and audio conferencing application (https://zoom.us/)
  hosts: localhost

  tasks:
    - name: Install Zoom video and audio conferencing application from web
      become: yes
      become_user: root
      become_method: sudo
      apt:
        deb: https://zoom.us/client/latest/zoom_amd64.deb
