---
# SEE: https://blogs.msdn.microsoft.com/commandline/2017/12/08/cross-post-wsl-interoperability-with-docker/
- name: Set up WSL Interoperability with Docker for Windows
  hosts: localhost

  tasks:
    - fail:
        msg: 'Bailing out, this play requires "windows_username" variable set to your Windows username. Example usage of this playbook: ansible-playbook -vv --ask-become-pass --extra-vars "windows_username=<your Windows username>" wsl_ubuntu/docker.yml'
      when: windows_username is not defined

    - name: Uninstall any previous Docker package
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name: 
          - docker
          - docker-engine
          - docker.io
        state: absent

    - name: Install go language
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name:
          - golang
        state: present
        update_cache: yes

    - name: Get the source for npiperelay 
      command: go get -d github.com/jstarks/npiperelay

    - name: Build npiperelay for windows_username
      command: env GOOS=windows go build -o /mnt/c/Users/{{windows_username}}/go/bin/npiperelay.exe github.com/jstarks/npiperelay

    - name: Symlink npiperelay for windows_username
      become: yes
      become_user: root
      become_method: sudo
      file:
        src: /mnt/c/Users/{{windows_username}}/go/bin/npiperelay.exe
        dest: /usr/local/bin/npiperelay.exe
        state: link

    - name: Install packages to allow apt to use a repository over HTTPS
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key to allow apt to authenticate the Docker repository
      become: yes
      become_user: root
      become_method: sudo
      apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         id: 0EBFCD88
         state: present
         validate_certs: yes

    - name: Add Docker APT list
      become: yes
      become_user: root
      become_method: sudo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
        filename: docker

    - name: Install Docker command line tools
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name:
          - docker-ce-cli
          - docker-compose
        state: present
        update_cache: yes

    - name: Add docker group
      become: yes
      become_user: root
      become_method: sudo
      command: groupadd docker

    - name: Add the current WSL user to the 'docker' group
      become: yes
      become_user: root
      become_method: sudo
      command: usermod -aG docker {{ansible_user_id}}

    - name: Install socat
      become: yes
      become_user: root
      become_method: sudo
      apt:
        name:
          - socat
        state: present
        update_cache: yes
      
    - name: Create docker-relay script
      copy:
       content: |
                #!/bin/sh
                exec socat UNIX-LISTEN:/var/run/docker.sock,fork,group=docker,umask=007 EXEC:"npiperelay.exe -ep -s //./pipe/docker_engine",nofork
       dest: /home/{{ansible_user_id}}/docker-relay
       mode: 0744

    - name: Print info about usage of the docker-relay script
      debug:
        msg:
          - "Windows Subsystem for Linux interoperability with Docker should be set up now. To test it open a new WSL shell to ensure your group membership is reset. Launch the relay in the background:"
          - ""
          - "  $ sudo ~/docker-relay &"
          - ""
          - "Now, run a docker command to test the waters. You should be greeted by the same output as if you ran the command from Windows."
          - ""
          - "With the recent addition of background processes in WSL, you can close out of WSL, open it later, and the relay we have built will continue to run. However, if you kill the socat process or do a hard reboot of your system, you will need to make sure you launch the relay in the background again when you first launch WSL."
          - ""
          - "For details about how does this work, see this article:"
          - "https://blogs.msdn.microsoft.com/commandline/2017/12/08/cross-post-wsl-interoperability-with-docker/"

